name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 20.9
          registry-url: 'https://registry.npmjs.org'
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
